# Generated by Django 6.1 on 2026-09-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Character portrait image', null=True, upload_to='characters/avatars/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='voice_sample',
            field=models.FileField(blank=True, help_text='Clean 6-10 second .wav file of character speaking (for voice cloning)', null=True, upload_to='characters/voices/'),
        ),
    ]
