# Generated by Django 6.1 on 2026-09-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Character name (e.g., Damon Salvatore)', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (e.g., damon-salvatore)', unique=True)),
                ('title', models.CharField(blank=True, help_text='e.g., The Snarky Vampire / The Original Hybrid', max_length=150)),
                ('system_prompt', models.TextField(help_text='Detailed instructions guiding Gemini to respond strictly in character.')),
                ('avatar', models.ImageField(help_text='Character portrait image', upload_to='characters/avatars/')),
                ('voice_sample', models.FileField(help_text='Clean 6-10 second .wav file of character speaking (for voice cloning)', upload_to='characters/voices/')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle character visibility on the frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
